### ISSUE TITLE
Cannot find storage file:// ./data/app/org.tvp.kirikiri2_free-bw9vy_-1amq5mcldam1lqg==/base.apk

### ISSUE THREAD

**Issue by narb-btb** [zeas2/Kirikiroid2#26] opened 2018-01-16 08:13 UTC
When i tap the file ends with .xp3, it goes "Cannot find storage file:// ./data/app/org.tvp.kirikiri2_free-bw9vy_-1amq5mcldam1lqg==/base.apk", how to solve this please?

**Comment by Demos25** [comment] 2018-01-16 22:50
you need to buy v1.3.4

**Comment by zeas2** [comment] 2018-06-15 06:17
Duplicate of #17

**Closed** 2018-06-15 06:19 UTC
Labels: duplicate
